### ISSUE TITLE
Function xyz not found in htslib

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/ruby-htslib#22]
Hey there kojix2,

    bam = HTS::Bam.open("foobar.bam")

I get some warnings I guess:

    Function 'bam_mods_query_type' not found in [/home/Programs/Htslib/1.15.1/lib/libhts.so]
    Function 'bam_mods_recorded' not found in [/home/Programs/Htslib/1.15.1/lib/libhts.so]

Not sure whether these are caused by the htslib gem, or by the upstream htslib.

If you can, and know whether this is an issue, and how to resolve it, perhaps the main
README could mention it. Or if it is a warning that could be suppressed. Anyway just
reporting here to let you know!

**Comment by kojix2** [comment]
Hello.

These error messages are intentional. It means that the shared library does not have the functions. If you are not using the latest htslib, you will always get this kind of error messages because htslib is a library still under development, and new functions are still being added. 

However, I think your point is very interesting. New users may be surprised to see the error message.

I would consider disabling this error message. Thank you for your reporting.

**Comment by kojix2** [comment]
Changed to warn only when Verbosity mode is enabled. Thank you for reporting.
https://idiosyncratic-ruby.com/3-ruby-can-you-speak-louder.html
![image](https://user-images.githubusercontent.com/5798442/188273168-96735b30-774f-4772-a199-2355f6014496.png)
